"""
Property Tests for Hypothesis Generator

**Feature: cyfer-brain, Property: Hypotheses never contain classifications**
**Validates: Requirements 1.3**
"""

import pytest
from hypothesis import given, strategies as st, settings
import sys
import os

# Add parent directory to path for import
test_dir = os.path.dirname(os.path.abspath(__file__))
cyfer_brain_dir = os.path.dirname(test_dir)
python_dir = os.path.dirname(cyfer_brain_dir)
if python_dir not in sys.path:
    sys.path.insert(0, python_dir)

from cyfer_brain.hypothesis import HypothesisGenerator, Target
from cyfer_brain.types import Hypothesis, HypothesisStatus, MCPClassification


class TestHypothesisGeneratorNeverClassifies:
    """
    **Feature: cyfer-brain, Property: Hypotheses never contain classifications**
    **Validates: Requirements 1.3**
    
    For any hypothesis generated by HypothesisGenerator, the hypothesis
    SHALL NOT have mcp_classification set — that's MCP's job.
    """
    
    def test_generate_from_recon_never_sets_classification(self):
        """Verify generate_from_recon never sets mcp_classification."""
        generator = HypothesisGenerator()
        
        target = Target(
            domain="example.com",
            endpoints=["/api/users", "/api/payments"],
            authentication_type="JWT",
            has_financial_features=True,
            has_workflow_features=True,
        )
        
        hypotheses = generator.generate_from_recon(target)
        
        for h in hypotheses:
            assert h.mcp_classification is None, \
                "HypothesisGenerator should NEVER set mcp_classification"
            assert h.status == HypothesisStatus.UNTESTED, \
                "Generated hypotheses should be UNTESTED"
    
    def test_generate_from_signal_never_sets_classification(self):
        """Verify generate_from_signal never sets mcp_classification."""
        generator = HypothesisGenerator()
        
        signal = MCPClassification(
            observation_id="test-signal",
            classification="SIGNAL",
            confidence=0.5,
        )
        
        hypotheses = generator.generate_from_signal(signal)
        
        for h in hypotheses:
            assert h.mcp_classification is None, \
                "HypothesisGenerator should NEVER set mcp_classification"
    
    @given(
        st.lists(st.text(min_size=1, max_size=50), min_size=1, max_size=5),
        st.booleans(),
        st.booleans(),
    )
    @settings(max_examples=50)
    def test_all_generated_hypotheses_are_untested(
        self, endpoints, has_financial, has_workflow
    ):
        """
        Property test: ALL generated hypotheses have status UNTESTED
        and mcp_classification is None.
        """
        generator = HypothesisGenerator()
        
        target = Target(
            domain="test.com",
            endpoints=endpoints,
            has_financial_features=has_financial,
            has_workflow_features=has_workflow,
        )
        
        hypotheses = generator.generate_from_recon(target)
        
        for h in hypotheses:
            assert h.status == HypothesisStatus.UNTESTED
            assert h.mcp_classification is None
    
    def test_prioritize_does_not_set_classification(self):
        """Verify prioritize does not modify mcp_classification."""
        generator = HypothesisGenerator()
        
        hypotheses = [
            Hypothesis(description="Test 1", testability_score=0.3),
            Hypothesis(description="Test 2", testability_score=0.8),
            Hypothesis(description="Test 3", testability_score=0.5),
        ]
        
        prioritized = generator.prioritize(hypotheses)
        
        for h in prioritized:
            assert h.mcp_classification is None


class TestHypothesisGeneratorTestability:
    """Test that testability_score is NOT confidence."""
    
    def test_testability_is_bounded(self):
        """Verify testability_score is always in [0, 1]."""
        generator = HypothesisGenerator()
        
        target = Target(
            domain="example.com",
            endpoints=["/api/test"],
            has_financial_features=True,
            has_workflow_features=True,
            authentication_type="JWT",
        )
        
        hypotheses = generator.generate_from_recon(target)
        
        for h in hypotheses:
            assert 0.0 <= h.testability_score <= 1.0
    
    def test_prioritize_sorts_by_testability(self):
        """Verify prioritize sorts by testability (highest first)."""
        generator = HypothesisGenerator()
        
        hypotheses = [
            Hypothesis(description="Low", testability_score=0.2),
            Hypothesis(description="High", testability_score=0.9),
            Hypothesis(description="Medium", testability_score=0.5),
        ]
        
        prioritized = generator.prioritize(hypotheses)
        
        # Should be sorted by testability descending
        assert prioritized[0].testability_score == 0.9
        assert prioritized[1].testability_score == 0.5
        assert prioritized[2].testability_score == 0.2
    
    @given(st.lists(st.floats(min_value=0.0, max_value=1.0, allow_nan=False), min_size=1, max_size=20))
    @settings(max_examples=50)
    def test_prioritize_maintains_descending_order(self, testability_scores):
        """Property test: prioritize always produces descending testability order."""
        generator = HypothesisGenerator()
        
        hypotheses = [
            Hypothesis(description=f"H{i}", testability_score=score)
            for i, score in enumerate(testability_scores)
        ]
        
        prioritized = generator.prioritize(hypotheses)
        
        # Verify descending order
        for i in range(len(prioritized) - 1):
            assert prioritized[i].testability_score >= prioritized[i + 1].testability_score


class TestHypothesisGeneratorSignalHandling:
    """Test handling of MCP SIGNAL classifications."""
    
    def test_generate_from_signal_only_accepts_signals(self):
        """Verify generate_from_signal only works with SIGNAL classification."""
        generator = HypothesisGenerator()
        
        # BUG classification should not generate follow-ups
        bug = MCPClassification(
            observation_id="test-bug",
            classification="BUG",
            invariant_violated="AUTH_001",
        )
        
        hypotheses = generator.generate_from_signal(bug)
        assert len(hypotheses) == 0, "Should not generate from BUG classification"
        
        # NO_ISSUE should not generate follow-ups
        no_issue = MCPClassification(
            observation_id="test-no-issue",
            classification="NO_ISSUE",
        )
        
        hypotheses = generator.generate_from_signal(no_issue)
        assert len(hypotheses) == 0, "Should not generate from NO_ISSUE classification"
    
    def test_generate_from_signal_creates_untested_hypotheses(self):
        """Verify follow-up hypotheses from signals are UNTESTED."""
        generator = HypothesisGenerator()
        
        signal = MCPClassification(
            observation_id="test-signal",
            classification="SIGNAL",
        )
        
        hypotheses = generator.generate_from_signal(signal)
        
        for h in hypotheses:
            assert h.status == HypothesisStatus.UNTESTED
            assert h.mcp_classification is None
