"""
Property Tests for Core Types

**Feature: cyfer-brain, Property 1: Hypothesis Generation Independence**
**Validates: Requirements 1.3, 8.1**

For any hypothesis generated by Cyfer Brain, the hypothesis SHALL NOT
contain a classification field or confidence score — these are MCP's responsibility.
"""

import pytest
from hypothesis import given, strategies as st, settings
from dataclasses import fields
import sys
import os

# Add parent directory to path for import
test_dir = os.path.dirname(os.path.abspath(__file__))
cyfer_brain_dir = os.path.dirname(test_dir)
python_dir = os.path.dirname(cyfer_brain_dir)
if python_dir not in sys.path:
    sys.path.insert(0, python_dir)

from cyfer_brain.types import (
    Hypothesis,
    HypothesisStatus,
    Observation,
    MCPClassification,
    ExplorationAction,
    ActionType,
    ExplorationStats,
    ExplorationBoundary,
    ExplorationSummary,
)


class TestHypothesisIndependence:
    """
    **Feature: cyfer-brain, Property 1: Hypothesis Generation Independence**
    **Validates: Requirements 1.3, 8.1**
    
    For any hypothesis generated by Cyfer Brain, the hypothesis SHALL NOT
    contain a classification field or confidence score.
    """
    
    def test_hypothesis_has_no_confidence_field(self):
        """Verify Hypothesis does not have a 'confidence' field."""
        field_names = [f.name for f in fields(Hypothesis)]
        
        assert "confidence" not in field_names, \
            "Hypothesis should not have a 'confidence' field — that's MCP's domain"
    
    def test_hypothesis_has_no_is_vulnerability_field(self):
        """Verify Hypothesis does not have an 'is_vulnerability' field."""
        field_names = [f.name for f in fields(Hypothesis)]
        
        assert "is_vulnerability" not in field_names, \
            "Hypothesis should not have an 'is_vulnerability' field — that's MCP's determination"
    
    def test_hypothesis_has_testability_score_not_confidence(self):
        """Verify Hypothesis has testability_score, which is NOT confidence."""
        field_names = [f.name for f in fields(Hypothesis)]
        
        assert "testability_score" in field_names, \
            "Hypothesis should have testability_score (measures ease of testing)"
        
        # Create a hypothesis and verify the field exists
        h = Hypothesis(description="Test hypothesis")
        assert hasattr(h, "testability_score")
        assert 0.0 <= h.testability_score <= 1.0
    
    def test_hypothesis_mcp_classification_is_optional(self):
        """Verify mcp_classification is Optional and defaults to None."""
        h = Hypothesis(description="Test hypothesis")
        
        assert h.mcp_classification is None, \
            "mcp_classification should default to None (set by MCP, not Cyfer Brain)"
    
    @given(
        st.text(min_size=1),
        st.lists(st.sampled_from(["Authorization", "Monetary", "Workflow", "Trust"])),
        st.floats(min_value=0.0, max_value=1.0, allow_nan=False),
    )
    @settings(max_examples=100)
    def test_hypothesis_creation_never_sets_classification(
        self, description, categories, testability
    ):
        """
        Property test: Creating a Hypothesis NEVER sets a classification.
        Classification is MCP's responsibility.
        """
        h = Hypothesis(
            description=description,
            target_invariant_categories=categories,
            testability_score=testability,
        )
        
        # Classification should always be None when created by Cyfer Brain
        assert h.mcp_classification is None, \
            "Hypothesis should never have classification set by Cyfer Brain"
        
        # Status should be UNTESTED
        assert h.status == HypothesisStatus.UNTESTED


class TestObservationNoClassification:
    """
    Verify Observation has no classification field.
    Classification is MCP's job.
    """
    
    def test_observation_has_no_classification_field(self):
        """Verify Observation does not have a 'classification' field."""
        field_names = [f.name for f in fields(Observation)]
        
        assert "classification" not in field_names, \
            "Observation should not have a 'classification' field — that's MCP's job"
    
    def test_observation_has_no_confidence_field(self):
        """Verify Observation does not have a 'confidence' field."""
        field_names = [f.name for f in fields(Observation)]
        
        assert "confidence" not in field_names, \
            "Observation should not have a 'confidence' field — that's MCP's domain"
    
    def test_observation_has_no_is_bug_field(self):
        """Verify Observation does not have an 'is_bug' field."""
        field_names = [f.name for f in fields(Observation)]
        
        assert "is_bug" not in field_names, \
            "Observation should not have an 'is_bug' field — that's MCP's determination"
    
    @given(
        st.dictionaries(st.text(min_size=1), st.text()),
        st.dictionaries(st.text(min_size=1), st.text()),
    )
    @settings(max_examples=100)
    def test_observation_captures_state_without_judgement(
        self, before_state, after_state
    ):
        """
        Property test: Observation captures state without making judgements.
        """
        obs = Observation(
            hypothesis_id="test",
            before_state=before_state,
            after_state=after_state,
        )
        
        # Observation should capture state
        assert obs.before_state == before_state
        assert obs.after_state == after_state
        
        # But should not have any judgement fields
        assert not hasattr(obs, "classification")
        assert not hasattr(obs, "is_bug")
        assert not hasattr(obs, "confidence")


class TestMCPClassificationReadOnly:
    """
    Verify MCPClassification is read-only from Cyfer Brain's perspective.
    """
    
    def test_mcp_classification_has_all_required_fields(self):
        """Verify MCPClassification has all fields MCP provides."""
        field_names = [f.name for f in fields(MCPClassification)]
        
        required_fields = [
            "observation_id",
            "classification",
            "invariant_violated",
            "proof",
            "confidence",
            "coverage_gaps",
        ]
        
        for field in required_fields:
            assert field in field_names, f"MCPClassification should have '{field}' field"
    
    @given(
        st.sampled_from(["BUG", "SIGNAL", "NO_ISSUE", "COVERAGE_GAP"]),
        st.floats(min_value=0.0, max_value=1.0, allow_nan=False),
    )
    @settings(max_examples=100)
    def test_mcp_classification_helper_methods(self, classification_type, confidence):
        """
        Property test: MCPClassification helper methods correctly identify type.
        """
        mc = MCPClassification(
            observation_id="test",
            classification=classification_type,
            confidence=confidence,
        )
        
        # Verify helper methods
        assert mc.is_bug() == (classification_type == "BUG")
        assert mc.is_signal() == (classification_type == "SIGNAL")
        assert mc.is_no_issue() == (classification_type == "NO_ISSUE")
        assert mc.is_coverage_gap() == (classification_type == "COVERAGE_GAP")


class TestExplorationSummaryNoCompleteness:
    """
    Verify ExplorationSummary does not claim completeness.
    """
    
    def test_exploration_summary_has_no_coverage_percentage(self):
        """Verify ExplorationSummary does not have coverage_percentage field."""
        field_names = [f.name for f in fields(ExplorationSummary)]
        
        assert "coverage_percentage" not in field_names, \
            "ExplorationSummary should not claim coverage percentage"
    
    def test_exploration_summary_has_no_is_complete_field(self):
        """Verify ExplorationSummary does not have is_complete field."""
        field_names = [f.name for f in fields(ExplorationSummary)]
        
        assert "is_complete" not in field_names, \
            "ExplorationSummary should not claim completeness"
    
    def test_exploration_summary_has_stopped_reason(self):
        """Verify ExplorationSummary has stopped_reason to explain why exploration stopped."""
        summary = ExplorationSummary()
        
        assert hasattr(summary, "stopped_reason")
        assert hasattr(summary, "boundary_status")


class TestExplorationStatsCountsMCPClassifications:
    """
    Verify ExplorationStats counts MCP classifications, not Cyfer Brain guesses.
    """
    
    def test_bugs_found_counts_mcp_classifications(self):
        """Verify bugs_found field exists and defaults to 0."""
        stats = ExplorationStats()
        
        assert hasattr(stats, "bugs_found")
        assert stats.bugs_found == 0  # No bugs until MCP classifies them
    
    def test_stats_has_all_classification_counters(self):
        """Verify stats has counters for all MCP classification types."""
        stats = ExplorationStats()
        
        assert hasattr(stats, "bugs_found")
        assert hasattr(stats, "signals_found")
        assert hasattr(stats, "no_issues")
        assert hasattr(stats, "coverage_gaps")
