"""
Phase-8 Data Models

All data models are FROZEN (immutable) dataclasses to ensure:
- Computed insights cannot be modified after creation
- No accidental mutation of output data
- Thread-safe read operations

SAFETY CONSTRAINTS:
- All models are frozen=True
- NO recommendation fields
- NO prediction fields
- NO validation fields
- NO ranking fields
- NO comparison fields
- All outputs include human_decision_required or human_interpretation_required
- All similarity scores include heuristic disclaimers

EXPLICIT NON-GOALS:
- NO validate_bug, is_true_positive, is_false_positive methods
- NO identify_business_logic_flaw, detect_logic_error methods
- NO generate_poc, generate_proof_of_concept, generate_exploit methods
- NO determine_cve, match_cve, assign_cve methods
- NO accuracy, confidence_score, guarantee_accuracy methods
- NO auto_submit, safe_submit, guided_submission methods
"""

from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional, Any


class InsightType(Enum):
    """Types of insights generated by Phase-8."""
    DUPLICATE_WARNING = "duplicate_warning"
    ACCEPTANCE_PATTERN = "acceptance_pattern"
    TARGET_PROFILE = "target_profile"
    PERFORMANCE_METRICS = "performance_metrics"
    PATTERN_INSIGHT = "pattern_insight"


# ============================================================================
# Duplicate Detection Types
# ============================================================================

@dataclass(frozen=True)
class SimilarFinding:
    """
    Reference to a similar historical finding.
    
    IMPORTANT: similarity_score is ADVISORY ONLY.
    - Even a score of 1.0 does NOT guarantee duplication
    - Even a score of 0.0 does NOT guarantee uniqueness
    - Human verification is ALWAYS required
    - This is a HEURISTIC estimate, not authoritative
    """
    finding_id: str
    decision_id: str
    similarity_score: float  # ADVISORY ONLY - heuristic, not authoritative
    decision_type: str  # From DecisionType enum value
    submission_status: Optional[str]  # From SubmissionStatus enum value
    submitted_at: Optional[datetime]
    score_disclaimer: str = "Advisory only - does not imply certainty"


@dataclass(frozen=True)
class DuplicateWarning:
    """
    Immutable warning about potential duplicate finding.
    
    NOTE: This is a WARNING only. It does NOT block any action.
    Human decides whether to proceed.
    
    IMPORTANT: Similarity is HEURISTIC, not authoritative.
    - Scores are advisory only
    - No score implies duplication certainty
    - Human verification is always required
    - Even 100% similarity does NOT guarantee duplication
    
    FORBIDDEN FIELDS (do not add):
    - block_action
    - auto_reject
    - is_duplicate
    - confirmed_duplicate
    - recommended_action
    """
    finding_id: str
    similar_findings: tuple[SimilarFinding, ...]
    highest_similarity: float
    warning_message: str
    similarity_disclaimer: str = "Heuristic estimate - human verification required"
    is_heuristic: bool = True  # Always True - similarity is never authoritative
    human_decision_required: bool = True  # Always True
    no_accuracy_guarantee: str = "No accuracy guarantee - human expertise required"


# ============================================================================
# Acceptance Pattern Types
# ============================================================================

@dataclass(frozen=True)
class AcceptancePattern:
    """
    Immutable acceptance rate statistics.
    
    NOTE: These are historical statistics only. They do NOT
    recommend any action. Human interprets the data.
    
    FORBIDDEN FIELDS (do not add):
    - recommended_platform
    - recommendation
    - suggested_action
    - priority_score
    - should_submit
    - best_platform
    """
    platform: str  # From Platform enum value
    vulnerability_type: Optional[str]
    severity: Optional[str]
    total_submissions: int
    accepted_count: int
    rejected_count: int
    pending_count: int
    acceptance_rate: float
    average_response_days: Optional[float]
    date_range_start: datetime
    date_range_end: datetime
    human_interpretation_required: bool = True  # Always True
    no_accuracy_guarantee: str = "No accuracy guarantee - human expertise required"


# ============================================================================
# Target Profile Types
# ============================================================================

@dataclass(frozen=True)
class TargetProfile:
    """
    Immutable profile of historical findings for a target.
    
    NOTE: This is HISTORICAL data only. It does NOT predict
    future vulnerabilities or recommend testing strategies.
    
    FORBIDDEN FIELDS (do not add):
    - predicted_vulnerabilities
    - future_risk
    - recommended_tests
    - suggested_focus
    - vulnerability_forecast
    - risk_score
    """
    target_id: str
    total_findings: int
    findings_by_decision: dict[str, int]  # DecisionType value -> count
    findings_by_severity: dict[str, int]  # Severity value -> count
    findings_by_type: dict[str, int]  # Vulnerability type -> count
    submissions_by_platform: dict[str, int]  # Platform value -> count
    submission_outcomes: dict[str, int]  # SubmissionStatus value -> count
    first_finding_date: Optional[datetime]
    last_finding_date: Optional[datetime]
    average_findings_per_month: float
    human_interpretation_required: bool = True  # Always True
    no_accuracy_guarantee: str = "No accuracy guarantee - human expertise required"


# ============================================================================
# Performance Metrics Types
# ============================================================================

@dataclass(frozen=True)
class PerformanceMetrics:
    """
    Immutable personal performance metrics.
    
    NOTE: These are PERSONAL metrics only.
    - No comparison with other reviewers
    - No rankings
    - No performance targets
    - No recommendations
    
    FORBIDDEN FIELDS (do not add):
    - rank
    - percentile
    - comparison
    - team_average
    - performance_target
    - other_reviewers
    - should_improve
    - recommendation
    """
    reviewer_id: str
    total_decisions: int
    decisions_by_type: dict[str, int]  # DecisionType value -> count
    average_review_time_seconds: float
    severity_distribution: dict[str, int]  # Severity value -> count
    submission_outcomes: dict[str, int]  # SubmissionStatus value -> count
    outcome_correlation: float  # Approved findings that were accepted
    reversal_rate: float  # Decisions overridden by senior
    date_range_start: datetime
    date_range_end: datetime
    human_interpretation_required: bool = True  # Always True
    no_accuracy_guarantee: str = "No accuracy guarantee - human expertise required"


# ============================================================================
# Pattern Insight Types
# ============================================================================

@dataclass(frozen=True)
class DataPoint:
    """Single data point in a trend."""
    timestamp: datetime
    value: float
    label: str


@dataclass(frozen=True)
class PatternInsight:
    """
    Immutable trend observation.
    
    NOTE: This is an OBSERVATION only. It does NOT predict
    or recommend any action. Human interprets the data.
    
    FORBIDDEN FIELDS (do not add):
    - predicted_value
    - forecast
    - expected_trend
    - recommended_action
    - should_do
    - best_action
    """
    insight_type: str
    description: str
    data_points: tuple[DataPoint, ...]
    trend_direction: Optional[str]  # "increasing", "decreasing", "stable", None
    confidence_note: str  # "Based on N data points"
    human_interpretation_required: bool = True  # Always True
    no_accuracy_guarantee: str = "No accuracy guarantee - human expertise required"


@dataclass(frozen=True)
class TimelineEntry:
    """Single entry in a timeline."""
    period: str
    count: int
    breakdown: dict[str, int]
